[package]
name = "rakun-application"
version = "0.1.0"
authors = ["mbsd <mbsd@m0x.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
async-trait = "0.1.42"
regex = "1.4.3"
thiserror = "1.0.23"
