[package]
name = "rk-client"
version = "0.0.1"
authors = ["mbsd <murilo.ijanc@kovi.com.br>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
reqwest = { version = "0.10.10", features = ["blocking", "json", "cookie"] }
url = "2.2.0"
