[package]
name = "rk-client"
version = "0.0.1"
authors = ["mbsd <murilo.ijanc@kovi.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
